In [42]:
#Import file
import pandas as pd

df = pd.read_csv('../Data/game_results/games_2026.csv')

In [43]:
df

,game_id,season,season_type,game_date,game_date_time,team_id,team_uid,team_slug,team_location,team_name,...,opponent_team_slug,opponent_team_location,opponent_team_name,opponent_team_abbreviation,opponent_team_display_name,opponent_team_short_display_name,opponent_team_color,opponent_team_alternate_color,opponent_team_logo,opponent_team_score
0,401808540,2026,2,3/2/2026,3/2/2026 22:00,2692,s:40~l:41~t:2692,weber-state-wildcats,Weber State,Wildcats,...,portland-state-vikings,Portland State,Vikings,PRST,Portland State Vikings,Portland St,00311e,ebebeb,https://a.espncdn.com/i/teamlogos/ncaa/500/250...,84
1,401808540,2026,2,3/2/2026,3/2/2026 22:00,2502,s:40~l:41~t:2502,portland-state-vikings,Portland State,Vikings,...,weber-state-wildcats,Weber State,Wildcats,WEB,Weber State Wildcats,Weber St,18005a,ebebeb,https://a.espncdn.com/i/teamlogos/ncaa/500/269...,60
2,401808500,2026,2,3/2/2026,3/2/2026 22:00,304,s:40~l:41~t:304,idaho-state-bengals,Idaho State,Bengals,...,sacramento-state-hornets,Sacramento State,Hornets,SAC,Sacramento State Hornets,Sacramento St,00573C,cdb97d,https://a.espncdn.com/i/teamlogos/ncaa/500/16.png,83
3,401808500,2026,2,3/2/2026,3/2/2026 22:00,16,s:40~l:41~t:16,sacramento-state-hornets,Sacramento State,Hornets,...,idaho-state-bengals,Idaho State,Bengals,IDST,Idaho State Bengals,Idaho St,ef8c00,e9a126,https://a.espncdn.com/i/teamlogos/ncaa/500/304...,65
4,401820821,2026,2,3/2/2026,3/2/2026 21:00,66,s:40~l:41~t:66,iowa-state-cyclones,Iowa State,Cyclones,...,arizona-wildcats,Arizona,Wildcats,ARIZ,Arizona Wildcats,Arizona,cc0033,3366,https://a.espncdn.com/i/teamlogos/ncaa/500/12.png,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11423,401830655,2026,2,11/3/2025,11/3/2025 11:30,2837,s:40~l:41~t:2837,east-texas-am-lions,East Texas A&M,Lions,...,arlington-baptist-patriots,Arlington Baptist,Patriots,ABU,Arlington Baptist Patriots,Arlington Bapt,NaN,NaN,NaN,60
11424,401817194,2026,2,11/3/2025,11/3/2025 11:00,71,s:40~l:41~t:71,bradley-braves,Bradley,Braves,...,st-bonaventure-bonnies,St. Bonaventure,Bonnies,SBU,St. Bonaventure Bonnies,St Bonaventure,70261D,NaN,https://a.espncdn.com/i/teamlogos/ncaa/500/179...,69
11425,401817194,2026,2,11/3/2025,11/3/2025 11:00,179,s:40~l:41~t:179,st-bonaventure-bonnies,St. Bonaventure,Bonnies,...,bradley-braves,Bradley,Braves,BRAD,Bradley Braves,Bradley,b70002,c0c0c0,https://a.espncdn.com/i/teamlogos/ncaa/500/71.png,63
11426,401823449,2026,2,11/3/2025,11/3/2025 8:00,2511,s:40~l:41~t:2511,queens-university-royals,Queens University,Royals,...,winthrop-eagles,Winthrop,Eagles,WIN,Winthrop Eagles,Winthrop,9e0b0e,fdb41e,https://a.espncdn.com/i/teamlogos/ncaa/500/273...,81
11427,401823449,2026,2,11/3/2025,11/3/2025 8:00,2737,s:40~l:41~t:2737,winthrop-eagles,Winthrop,Eagles,...,queens-university-royals,Queens University,Royals,QUC,Queens University Royals,Queens,NaN,NaN,https://a.espncdn.com/i/teamlogos/ncaa/500/251...,74

In [44]:
df = df.drop(columns=[col for col in df.columns if col.startswith('opponent_')])

In [45]:
for col in df.columns:
    print(col)

game_id
season
season_type
game_date
game_date_time
team_id
team_uid
team_slug
team_location
team_name
team_abbreviation
team_display_name
team_short_display_name
team_color
team_alternate_color
team_logo
team_home_away
team_score
team_winner
assists
blocks
defensive_rebounds
field_goal_pct
field_goals_made
field_goals_attempted
flagrant_fouls
fouls
free_throw_pct
free_throws_made
free_throws_attempted
largest_lead
offensive_rebounds
steals
team_turnovers
technical_fouls
three_point_field_goal_pct
three_point_field_goals_made
three_point_field_goals_attempted
total_rebounds
total_technical_fouls
total_turnovers
turnovers

In [46]:
drop_cols = ['game_date_time','team_uid','team_location','team_slug','team_name','team_abbreviation','team_display_name','team_short_display_name','team_color','team_alternate_color','team_logo']
df.drop(columns=drop_cols,inplace=True)

In [47]:
for col in df.columns:
    print(col)

game_id
season
season_type
game_date
team_id
team_home_away
team_score
team_winner
assists
blocks
defensive_rebounds
field_goal_pct
field_goals_made
field_goals_attempted
flagrant_fouls
fouls
free_throw_pct
free_throws_made
free_throws_attempted
largest_lead
offensive_rebounds
steals
team_turnovers
technical_fouls
three_point_field_goal_pct
three_point_field_goals_made
three_point_field_goals_attempted
total_rebounds
total_technical_fouls
total_turnovers
turnovers

In [62]:
df_merged = df.merge(df, on=["game_id","season","season_type","game_date"], suffixes=(None,"_opponent"))
df_merged = df_merged[df_merged["team_id"] != df_merged["team_id_opponent"]]

In [63]:
df_merged

,game_id,season,season_type,game_date,team_id,team_home_away,team_score,team_winner,assists,blocks,...,technical_fouls_opponent,three_point_field_goal_pct_opponent,three_point_field_goals_made_opponent,three_point_field_goals_attempted_opponent,total_rebounds_opponent,total_technical_fouls_opponent,total_turnovers_opponent,turnovers_opponent,poss_opponent,off_eff_opponent
1,401808540,2026,2,3/2/2026,2692,away,60,False,8,0,...,0,32,7,22,36,0,7,7,60.650,138.499588
2,401808540,2026,2,3/2/2026,2502,home,84,True,25,5,...,0,24,5,21,33,0,14,14,57.225,104.849279
5,401808500,2026,2,3/2/2026,304,away,65,False,14,4,...,0,39,7,18,33,0,9,9,60.925,136.233073
6,401808500,2026,2,3/2/2026,16,home,83,True,21,4,...,0,21,6,29,32,0,12,12,57.975,112.117292
9,401820821,2026,2,3/2/2026,66,away,57,False,10,2,...,0,33,6,18,40,0,15,15,52.350,139.446036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22846,401830655,2026,2,11/3/2025,2837,home,119,True,35,4,...,0,27,4,15,27,0,26,26,58.875,101.910828
22849,401817194,2026,2,11/3/2025,71,away,63,False,12,2,...,0,36,8,22,44,0,13,13,54.075,127.600555
22850,401817194,2026,2,11/3/2025,179,home,69,True,14,7,...,0,27,6,22,29,0,9,9,57.175,110.188019
22853,401823449,2026,2,11/3/2025,2511,away,74,False,10,1,...,0,32,8,25,39,0,10,10,60.725,133.388226
22854,401823449,2026,2,11/3/2025,2737,home,81,True,12,4,...,0,20,6,30,39,0,17,17,56.600,130.742049

In [ ]:
for col in df_merged.columns:
    print(col)

game_id
season
season_type
game_date
team_id
team_home_away
team_score
team_winner
assists
blocks
defensive_rebounds
field_goal_pct
field_goals_made
field_goals_attempted
flagrant_fouls
fouls
free_throw_pct
free_throws_made
free_throws_attempted
largest_lead
offensive_rebounds
steals
team_turnovers
technical_fouls
three_point_field_goal_pct
three_point_field_goals_made
three_point_field_goals_attempted
total_rebounds
total_technical_fouls
total_turnovers
turnovers
poss
off_eff
team_id_opponent
team_home_away_opponent
team_score_opponent
team_winner_opponent
assists_opponent
blocks_opponent
defensive_rebounds_opponent
field_goal_pct_opponent
field_goals_made_opponent
field_goals_attempted_opponent
flagrant_fouls_opponent
fouls_opponent
free_throw_pct_opponent
free_throws_made_opponent
free_throws_attempted_opponent
largest_lead_opponent
offensive_rebounds_opponent
steals_opponent
team_turnovers_opponent
technical_fouls_opponent
three_point_field_goal_pct_opponent
three_point_field_goals_made_opponent
three_point_field_goals_attempted_opponent
total_rebounds_opponent
total_technical_fouls_opponent
total_turnovers_opponent
turnovers_opponent
poss_opponent
off_eff_opponent

In [ ]:
# Core Predictors
df['poss'] = df['field_goals_attempted'] - df['offensive_rebounds'] + df['team_turnovers'] + (0.475 * df['free_throws_attempted'])
df['off_eff'] = (df['team_score'] / df['poss']) * 100

In [ ]:
# Four Factors
df['efg'] = (df['field_goals_made'] + (0.5 * df['three_point_field_goals_made']))/df['field_goals_attempted']
df['tov'] = df['team_turnovers'] / df['poss']
df['orb'] =

Add:
AdjD = (opponent_score / opponent_poss) * 100
Net Efficiency = AdjO - AdjD
Net Efficiency Differential = TeamA_net - TeamB_net